This week we will be learning about aggregations and using them to do a deeper investigation into the effects of different types of joins. 

We will also do a few problems exploring matrix inverses.

### Tutorials
- https://www.datacamp.com/community/tutorials/pandas-multi-index
- https://www.datacamp.com/community/tutorials/pandas-split-apply-combine-groupby

## Grouping Data

The expressiveness of Python and pandas allows complex group operations using any function that accepts a pandas object or NumPy array. This can include:

- Splitting a pandas object into pieces using one or more keys
- Calculating group summary statistics
- Applying within-group transformations or other manipulations
- Computing pivot tables and cross-tabulations
- Performing quantile analysis and other statistical group analyses

### GroupBy Operations

Group operations involve the `split-apply-combine` mechanism.

1. Data are split into groups based on one or more keys
2. A function is applied to each group
3. Results of the function application are combined into a new object

Grouping keys can take many forms, and the keys do not have to be all of the same type.

pandas `groupby` method returns a GroupBy object that can be re-used.

DataFrame columns can be used as the group keys.

Numeric aggregations will exclude `nuisance` (non-numeric) columns from the result

By default `groupby` groups on axis=0, but can group on any of the other axes.

### Iterating over groups

The GroupBy object supports iteration, generating a sequence of 2-tuples containing the group name along with the chunk of data.

Indexing a GroupBy object created from a DataFrame with a column name or array of column names has the effect of column subsetting for aggregation. This means that:
```
df.groupby('key1')['data1']
```
is essentially the same as:
```
df['data1'].groupby(df['key1'])
```

### Reindexing

The output of GroupBys are often multi-indexed. This is typically not the form you want for your analysis. This means that you will want to reset your index or remove multi indexes on your columns. See below for examples of that.

In [23]:
import pandas as pd
import numpy as np

speeds = pd.DataFrame(
    [
        ("bird", "Falconiformes", 389.0, 0),
        ("bird", "Psittaciformes", 24.0, 0),
        ("mammal", "Carnivora", 80.2, 0),
        ("mammal", "Primates", np.nan, 0),
        ("mammal", "Carnivora", 58, 0),
    ],
    index=["falcon", "parrot", "lion", "monkey", "leopard"],
    columns=("class", "order", "max_speed", 'min_speed'),
)

not_reindexed = speeds.groupby(["class", "order"]).agg(['sum', 'mean'])
not_reindexed

                      max_speed        min_speed
                            sum   mean       sum mean
class  order
bird   Falconiformes      389.0  389.0         0  0.0
       Psittaciformes      24.0   24.0         0  0.0
mammal Carnivora          138.2   69.1         0  0.0
       Primates             0.0    NaN         0  0.0

In [24]:
not_reindexed.columns = ["_".join(i) for i in not_reindexed.columns]
not_reindexed

                       max_speed_sum  max_speed_mean  min_speed_sum  \
class  order
bird   Falconiformes           389.0           389.0              0
       Psittaciformes           24.0            24.0              0
mammal Carnivora               138.2            69.1              0
       Primates                  0.0             NaN              0

                       min_speed_mean
class  order
bird   Falconiformes              0.0
       Psittaciformes             0.0
mammal Carnivora                  0.0
       Primates                   0.0

In [25]:
not_reindexed.reset_index()

,class,order,max_speed_sum,max_speed_mean,min_speed_sum,min_speed_mean
0,bird,Falconiformes,389.0,389.0,0,0.0
1,bird,Psittaciformes,24.0,24.0,0,0.0
2,mammal,Carnivora,138.2,69.1,0,0.0
3,mammal,Primates,0.0,NaN,0,0.0

### All Data Descriptions


* `customers` - A table of customers. The unique id for the customer is `customer_id` meaning only one id per customer. 
* `orders` - A table of orders. The unique id for the order is `order_id` there is a foreign key (`customer_id`) that tells you which customer placed the order.
* `web_visits`: Describes visitors to the website, with `visitor_id` be a unique id per visitor to the website. If the visitor is a logged in customer then the `customer_id` has a value otherwise it is null. 
* `ad_clicks`: Describes clicks on ad on an external website, the `external_user_id` is an unique id per user from the external website. If the user is a known in customer then the `customer_id` has a value otherwise it is null.

In [26]:
import generate_week_10_data

customers, orders, web_visits, ad_clicks = generate_week_10_data.create_data()

### Problem 1 (10 pts)

1. What is the order amount per `customer_name`, only include customers who have orders
2. What is the order amount per `customer_name`, include customers even if they have no orders

#### Grading: 
5 points per question. 2 points for the correct join and 3 point for the aggragations.

In [ ]:

order_customer = orders.merge(customers, on='customer_id', how='inner')
order_by_customer = order_customer.groupby('customer_name', as_index=False)['order_amount'].sum().sort_values('order_amount', ascending=False)

all_customer_orders = customers.merge(orders, on='customer_id', how='left')
all_order_by_customer = all_customer_orders.groupby('customer_name', as_index=False)['order_amount'].sum().fillna(0)

order_by_customer,  all_order_by_customer

(   customer_name  order_amount
 1        chyloid   1648.153348
 4     lamnectomy   1583.329018
 6   receivership   1215.266089
 2      dermatoma    997.920841
 5  rapscallionly    997.713906
 7          shita    866.183315
 3    digitogenin    709.626087
 8       tasselet    547.586156
 0      amputator    392.529244,
    customer_name  order_amount
 0      amputator    392.529244
 1        chyloid   1648.153348
 2      dermatoma    997.920841
 3    digitogenin    709.626087
 4     lamnectomy   1583.329018
 5  rapscallionly    997.713906
 6   receivership   1215.266089
 7         septal      0.000000
 8          shita    866.183315
 9       tasselet    547.586156)

### Problem 2 (5 pts)
If you look at the raw results of the join you can visually see that there are duplicates for the columns that started in the `customer` table. This wasn't a concern above because we we doing an aggregation on a column in the `orders` table. Let's think through problems that require a join but are looking to do an aggregation with a column from the `customers` table. 

1. What is the average `customer_age` for customers who have placed orders. For this problem print the accurate average `customer_age` with duplicates remove and also print the inaccure average `customer_age` without duplicates removed. 
2. What is the average `customer_age` for customers who have placed orders versus those who haven't. 

#### Grading: 
5 points per question. 2 points for the correct join and 3 point for the aggragations.

In [28]:
# 1) accurate and inaccurate avg customer_age for customers with orders
joined = orders.merge(customers, on='customer_id', how='inner')
accurate_age = joined[['customer_id','customer_age']].drop_duplicates().customer_age.mean()
inaccurate_age = joined.customer_age.mean()

# 2) average customer_age for customers with and without orders
has_order = customers[customers.customer_id.isin(orders.customer_id.unique())]
no_order = customers[~customers.customer_id.isin(orders.customer_id.unique())]
avg_with = has_order.customer_age.mean()
avg_without = no_order.customer_age.mean()

accurate_age, inaccurate_age, avg_with, avg_without

(np.float64(13.37020780941142),
 np.float64(11.238533777962948),
 np.float64(13.37020780941142),
 np.float64(27.767543157602855))

### Problem 3 

Per customer what is the total number of web visits and ads clicked on? 

For this problem I want you to start with the `customers_visits_clicks_raw` table below and again do an accurate count that only counts a web visit once and an inaccurate count that counts duplications. Here is what the results should look like: 

<img src="images/number_visits_clicks.png" width="800"/>


#### Grading: 
5 points for joining correctly. 5 points for the correct aggragtions.

In [29]:
# Start with this dataset 
customers_visits_clicks_raw = customers.merge(web_visits, on="customer_id", how="left").merge(ad_clicks, on="customer_id", how="left")

# accurate count: unique visits and clicks each customer
accurate = customers_visits_clicks_raw.groupby(['customer_id','customer_name'], as_index=False).agg(
    total_web_visits=('interaction_id', 'nunique'),
    total_ad_clicks=('click_id', 'nunique')
)

# inaccurate count: duplicates counted from joined table
inaccurate = customers_visits_clicks_raw.groupby(['customer_id','customer_name'], as_index=False).agg(
    total_web_visits=('interaction_id', 'count'),
    total_ad_clicks=('click_id', 'count')
)

accurate.head(), inaccurate.head()

(   customer_id customer_name  total_web_visits  total_ad_clicks
 0            1        septal                 2                1
 1            2    lamnectomy                 1                1
 2            3   digitogenin                 0                1
 3            4         shita                 1                1
 4            5     dermatoma                 0                1,
    customer_id customer_name  total_web_visits  total_ad_clicks
 0            1        septal                 2                2
 1            2    lamnectomy                 1                1
 2            3   digitogenin                 0                1
 3            4         shita                 1                1
 4            5     dermatoma                 0                1)

### Problem 4 (5 pts)

We will now work through a problem with outer joins.

Create a dataframe with the daily number of: 
* web visits
* unique web visitors
* unique customers visiting website
* ads clicks
* unique users clicking
* unique customers clicking

You should include the full date range 2024-05-01 to 2024-05-09 even though not all dates are included in either dataframe. 

You will create this data frame two ways:
1. Join `web_visits` to `ad_clicks` first and then perform the calculations
2. Create aggregate dataframes for `web_visits` to `ad_clicks` first and then join those aggregate dataframes together

#### Grading: 
5 points per method. 2 points for the correct join and 3 point for the aggragations.

In [30]:
# Problem 4
import pandas as pd

date_range = pd.date_range('2024-05-01', '2024-05-09')

# Method 1: join first then aggregate
joined = web_visits.merge(ad_clicks, on='date', how='outer', suffixes=('_visit', '_click'))

method1 = (joined.groupby('date', as_index=False).agg(
    web_visits=('interaction_id', 'nunique'),
    unique_web_visitors=('visitor_id', 'nunique'),
    unique_customers_visiting=('customer_id_visit', lambda s: s.dropna().nunique()),
    ad_clicks=('click_id', 'nunique'),
    unique_users_clicking=('external_user_id', 'nunique'),
    unique_customers_clicking=('customer_id_click', lambda s: s.dropna().nunique())
))

method1 = method1.set_index('date').reindex(date_range, fill_value=0).reset_index().rename(columns={'index':'date'})

# Method 2: aggregate first then join
web_aggs = (web_visits.groupby('date', as_index=False).agg(
    web_visits=('interaction_id', 'nunique'),
    unique_web_visitors=('visitor_id', 'nunique'),
    unique_customers_visiting=('customer_id', lambda s: s.dropna().nunique())
))
ad_aggs = (ad_clicks.groupby('date', as_index=False).agg(
    ad_clicks=('click_id', 'nunique'),
    unique_users_clicking=('external_user_id', 'nunique'),
    unique_customers_clicking=('customer_id', lambda s: s.dropna().nunique())
))

method2 = web_aggs.merge(ad_aggs, on='date', how='outer').set_index('date').reindex(date_range).fillna(0).reset_index().rename(columns={'index':'date'})

method1, method2

(        date  web_visits  unique_web_visitors  unique_customers_visiting  \
 0 2024-05-01           4                    4                          1
 1 2024-05-02           5                    5                          2
 2 2024-05-03           5                    5                          3
 3 2024-05-04           5                    5                          2
 4 2024-05-05           1                    1                          0
 5 2024-05-06           0                    0                          0
 6 2024-05-07           0                    0                          0
 7 2024-05-08           0                    0                          0
 8 2024-05-09           0                    0                          0

    ad_clicks  unique_users_clicking  unique_customers_clicking
 0          0                      0                          0
 1          0                      0                          0
 2          2                      1                          1
 3          3                      3                          3
 4          3                      3                          2
 5          3                      3                          2
 6          3                      3                          2
 7          3                      3                          2
 8          3                      3                          0  ,
         date  web_visits  unique_web_visitors  unique_customers_visiting  \
 0 2024-05-01         4.0                  4.0                        1.0
 1 2024-05-02         5.0                  5.0                        2.0
 2 2024-05-03         5.0                  5.0                        3.0
 3 2024-05-04         5.0                  5.0                        2.0
 4 2024-05-05         1.0                  1.0                        0.0
 5 2024-05-06         0.0                  0.0                        0.0
 6 2024-05-07         0.0                  0.0                        0.0
 7 2024-05-08         0.0                  0.0                        0.0
 8 2024-05-09         0.0                  0.0                        0.0

    ad_clicks  unique_users_clicking  unique_customers_clicking
 0        0.0                    0.0                        0.0
 1        0.0                    0.0                        0.0
 2        2.0                    1.0                        1.0
 3        3.0                    3.0                        3.0
 4        3.0                    3.0                        2.0
 5        3.0                    3.0                        2.0
 6        3.0                    3.0                        2.0
 7        3.0                    3.0                        2.0
 8        3.0                    3.0                        0.0  )

### Problem 5 (15 pts)

Using the same two methods as problem 4 attempt to include:
* mean time on page per date 
* total time on page per date

One method will lead to some incorrect values unless you do a bit more work to correct the values. 

Write out a which method leads to correct values, which leads to incorrect values and why. 

#### Grading: 
* 5 points per method. 2 points for the correct join and 3 point for the aggragations. 
* 5 points for the written explaination.

In [31]:
# Problem 5
import pandas as pd

date_range = pd.date_range('2024-05-01', '2024-05-09')

# Method 1: join then compute (can double count time_on_page when multiple clicks per visit date)
joined = web_visits.merge(ad_clicks, on='date', how='outer', suffixes=('_visit', '_click'))
method1_time = (joined.groupby('date', as_index=False).agg(
    total_time_on_page=('time_on_page', 'sum'),
    mean_time_on_page=('time_on_page', 'mean')
))
method1_time = method1_time.set_index('date').reindex(date_range).fillna(0).reset_index().rename(columns={'index':'date'})

# Method 2: aggregate web_visits first then join
web_time = (web_visits.groupby('date', as_index=False).agg(
    total_time_on_page=('time_on_page', 'sum'),
    mean_time_on_page=('time_on_page', 'mean')
))
method2_time = web_time.set_index('date').reindex(date_range).reset_index().rename(columns={'index':'date'}).fillna(0)

method1_time, method2_time

(        date  total_time_on_page  mean_time_on_page
 0 2024-05-01          155.820856          38.955214
 1 2024-05-02          266.909141          53.381828
 2 2024-05-03          602.497325          60.249733
 3 2024-05-04          340.087556          22.672504
 4 2024-05-05          167.273457          55.757819
 5 2024-05-06            0.000000           0.000000
 6 2024-05-07            0.000000           0.000000
 7 2024-05-08            0.000000           0.000000
 8 2024-05-09            0.000000           0.000000,
         date  total_time_on_page  mean_time_on_page
 0 2024-05-01          155.820856          38.955214
 1 2024-05-02          266.909141          53.381828
 2 2024-05-03          301.248663          60.249733
 3 2024-05-04          113.362519          22.672504
 4 2024-05-05           55.757819          55.757819
 5 2024-05-06            0.000000           0.000000
 6 2024-05-07            0.000000           0.000000
 7 2024-05-08            0.000000           0.000000
 8 2024-05-09            0.000000           0.000000)

In [32]:

n = 4
A = np.random.randn(n, n)
while np.linalg.matrix_rank(A) != n:
    A = np.random.randn(n, n)

aug = np.hstack([A.astype(float), np.eye(n)])

# Gauss-Jordan elimination
for i in range(n):
    pivot = aug[i, i]
    aug[i] = aug[i] / pivot
    for j in range(n):
        if j != i:
            factor = aug[j, i]
            aug[j] = aug[j] - factor * aug[i]

A_inv = aug[:, n:]

print('Original A:')
print(A)
print('Computed A_inv:')
print(A_inv)
print('Check A @ A_inv (should be I):')
print(np.round(A @ A_inv, 6))

Original A:
[[ 1.38323223  0.34623312  1.02251611  0.16681027]
 [ 1.65671662  0.66788961 -0.22994664 -1.12955119]
 [-0.6399626   0.31383052 -1.22583598 -0.22179314]
 [ 1.33992631  0.02930971  1.98538575  1.4471656 ]]
Computed A_inv:
[[-3.77532729  2.03153076 -0.34218441  1.96839062]
 [ 6.84921315 -2.81347916  1.86971594 -2.69892931]
 [ 4.14629071 -1.92989806 -0.2779131  -2.02685977]
 [-2.33150551  0.82364648  0.66023251  1.70381673]]
Check A @ A_inv (should be I):
[[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0. -0.  1. -0.]
 [-0.  0.  0.  1.]]

### Problem 7 (15 pts)

The LIVE EVIL rule applies to the inverse of multiplied matrices. Test this in code by creating two square full-rank matrices $A$ and $B$, then use Euclidean distance to compare:
1. $(AB)^{-1}$ 
2. $A^{-1}B^{-1}$
3. $B^{-1}A^{-1}$

Before starting to code, make a prediction about which results will be equal. Print out your results using formatting like the following:

```
Distance between (AB)^-1 and (A^-1)(B^-1) is ___
Distance between (AB)^-1 and (B^-1)(A^-1) is ___
Distance between (A^-1)(B^-1) and (B^-1)(A^-1) is ___
```

#### Grading: 
5 points per comparision.

In [33]:

n = 4
A = np.random.randn(n, n)
B = np.random.randn(n, n)
while np.linalg.matrix_rank(A) != n or np.linalg.matrix_rank(B) != n:
    A = np.random.randn(n, n)
    B = np.random.randn(n, n)

A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
AB_inv = np.linalg.inv(A @ B)

cand1 = A_inv @ B_inv
cand2 = B_inv @ A_inv

d1 = np.linalg.norm(AB_inv - cand1)
d2 = np.linalg.norm(AB_inv - cand2)
d3 = np.linalg.norm(cand1 - cand2)

print(f"Distance between (AB)^-1 and (A^-1)(B^-1) is {d1:.8f}")
print(f"Distance between (AB)^-1 and (B^-1)(A^-1) is {d2:.8f}")
print(f"Distance between (A^-1)(B^-1) and (B^-1)(A^-1) is {d3:.8f}")

Distance between (AB)^-1 and (A^-1)(B^-1) is 4.85235640
Distance between (AB)^-1 and (B^-1)(A^-1) is 0.00000000
Distance between (A^-1)(B^-1) and (B^-1)(A^-1) is 4.85235640