# Intro to Pandas
___

**pandas** provides data structures and data manipulation tools designed for fast & easy data cleaning and analysis.

pandas adopts array-based computing from NumPy, but is designed for **tabular** or **heterogenous** data.

pandas has two primary data structures:

- **Series** - one-dimensional array-like object with a sequence of values having the same datatype
- **DataFrame** - rectangular table of data with ordered collection of columns, each of which can be a different value type

In [6]:
#As allways we import pandas and numpy
import pandas as pd
import numpy as np

### Series

Has a sequence of values (all the same datatype) and an associated array of data labels called its **index**. If not specified otherwise, the index values are sequential integers.

pandas can automatically determine datatype of values when a Series is created, but datatype can also be specified.

A Series is like a fixed-length, ordered dict with a mapping of index values to data values.

The array representation and index object of a Series can be accessed via its **values** and **index** attributes.

Problem 1: Create a series 4 numerical values. Print the series, the values and the index of the series.

In [7]:
pdseries = pd.Series([1, 2, -2, 1])
print(pdseries)

0    1
1    2
2   -2
3    1
dtype: int64

Problem 2: Create a new series with the same values but with string values for the index. Select and print out one of the values in the series with the index.

In [8]:
pdseries = pd.Series([1, 2, -2, 1], index=["d", "b", "a", "c"])
print(pdseries)
print(pdseries.index)

d    1
b    2
a   -2
c    1
dtype: int64
Index(['d', 'b', 'a', 'c'], dtype='str')

Problem 3: You can also create a series from a python dict. Create a dict called `states_dict` with the state name as the key and the number as the value.
'Ohio' 35000
'Texas' 71000
'Oregon' 16000 
'Utah' 5000
Use the dict `states_dict` to create a series called `states_series`.

In [9]:
states_dict = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
states = pd.Series(states_dict)

Problem 4: Updated the index of `state_series` to be the abbreviation of the state names. Do this in place.

In [ ]:
states_abbr = {
    "Ohio": "OH",
    "Texas": "TX",
    "Oregon": "OR",
    "Utah": "UT"
}
states.rename(index=states_abbr, inplace=True)

print(states)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### DataFrame

A pandas DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type.

Sort of a dict of Series all sharing the same index.

- DataFrames have both row and column indices
- DataFrames are physically 2D, but can represent higher-dimensional data using hierarchical indexing
- DataFrame rows are sometimes referred to as axis=0
- DataFrame columns are sometimes referred to as axis=1


You can create DataFrames from dicts as well.

In [ ]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
      }

df = pd.DataFrame(data)
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Problem 5: Update the index of the DataFrame df to be the words for each number. i.e. 1 -> one

Problem 6: Figure out two ways to access a column from df. Output the results.

In [ ]:
 pd.DataFrame(data, columns=["year"])

   year
0  2000
1  2001
2  2002
3  2001
4  2002
5  2003

Problem 7: Figure out two ways to access a row from df. Output the results.

In [ ]:
# pd.DataFrame(data, row=0)
print(data.loc[1])

AttributeError: 'dict' object has no attribute 'loc'

Problem 8: Add a new column to your dataframe called 'rating' with the values `[5,4,3,2,1,0]`

In [ ]:
# datanew = {
#     'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
#     'year': [2000, 2001, 2002, 2001, 2002, 2003],
#     'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
#     'rating': [5,4,3,2,1,0]
#       }
# df = pd.DataFrame(datanew)
# df

df["rating"] = [5,4,3,2,1,0]
df
#print(pd.DataFrame(data))

    state  year  pop  rating
0    Ohio  2000  1.5       5
1    Ohio  2001  1.7       4
2    Ohio  2002  3.6       3
3  Nevada  2001  2.4       2
4  Nevada  2002  2.9       1
5  Nevada  2003  3.2       0

Problem 9: Create another column called `nonsense` that is the rating multiplied by the pop.

Problem 10: Create three series using using numpy.

* series_numerical: The values 0-4 with index a-e
* series_zeros: All zeros with index a-e
* series_random: 5 random numbers qith index a-e

DataFrame called `numeric_df` from these three series. Each series will be a row and the columns will be a-e.

In [ ]:
idx = ['a', 'b', 'c', 'd', 'e']
series_numerical = pd.Series(np.arange(5), index = idx)
series_zeros = pd.Series(np.zeros(5), index = idx)
series_random = pd.Series(np.random.rand(5), index = idx)

series_list = pd.DataFrame((series_numerical,series_zeros, series_random))

series_list

          a         b         c         d         e
0  0.000000  1.000000  2.000000  3.000000  4.000000
1  0.000000  0.000000  0.000000  0.000000  0.000000
2  0.687466  0.560911  0.683826  0.804999  0.403294

Problem 11: Transpose the DataFrame `numeric_df` so that the series become columns instead of rows. Save this to a variable called `transposed_numeric_df`. Rename the columns to `numerical`, `zeros`, and `random`.

In [ ]:
transposed_numeric_df = series_list.T
transposed_numeric_df

     0    1         2
a  0.0  0.0  0.687466
b  1.0  0.0  0.560911
c  2.0  0.0  0.683826
d  3.0  0.0  0.804999
e  4.0  0.0  0.403294

Problem 12: Output `transposed_numeric_df` ordered by `random` descending.

In [ ]:
transposed_numeric_df
tr

Problem 13: Select all rows from `transposed_numeric_df` where the column `numerical` is greater than 2.

Problem 14: Add a column called `random_5` that is the column random multiplied by 5. Select all rows from `transposed_numeric_df` where `numerical` is greater than `random_5`.

In [ ]:
random_5 =

Problem 15: Add a column to transposed_numberic_df called `even` that is True when `numerical` is even and `False` when `numerical` is odd.

Problem 16: Add a column called `even_odd` that has the value `odd` when `numerical` is odd and `even` when `numerical` is even.

Problem 17: Print out the sum of all columns.

Problem 18: Print out index of the row with the max value for each column. i.e. for `numerical` it will be the last row `e` because it has a value of 5.